import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Services from '../components/Services';
import { Saira } from 'next/font/google';
import NewItems from '../components/newitems';
import About from '../components/About';
import Products from '../components/Products';
import Review from '../components/Review';

const saira = Saira({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.container} ${saira.className}`}>
        <Navbar />
        <Hero />
        <Services />
        <NewItems />
        <About />
        <Products />
        <Review />
      </div>
    </>
  );
}